### ISSUE TITLE
Optional aliases for untyped operations in handler pattern

### ISSUE THREAD

**Issue by droserasprout** [dipdup-net/dipdup#408]
Example config:

```yaml
- callback: on_something
  pattern:
    - type: transaction
      alias: approve
    - type: transaction
      destination: <contract>
      entrypoint: transfer
```

Codegened handler:

```python
async def on_something(
    ctx: HandlerContext,
    approve: OperationData,
    transfer: Transaction[TransferParameter, ContractStorage],
) -> None:
```
