### ISSUE TITLE
Missing `transactionId` in event

### ISSUE THREAD

**Issue by 0xflo-tez** [dipdup-net/dipdup#521]
**Steps to reproduce:**
Use the following dipdup config, and start the indexing

```
spec_version: 1.2

datasources:
  tzkt:
    kind: tzkt
    url: ${TZKT_URL:-https://api.ghostnet.tzkt.io}
    http:
      connection_timeout: 60

contracts:
  rarible_aggregator_tracker:
    address: KT1DajvCNVScudRm3kCHPfUjsRCtmPnm375s
    typename: rarible_aggregator_tracker

indexes:
  rarible_aggregator_tracker_events:
    kind: event
    datasource: tzkt
    handlers:
      - callback: on_rarible_aggregator_event
        contract: rarible_aggregator_tracker
        tag: aggregator_event
```

**What did you expect to happen:**
`transactionId` should be filled 
**What actually happened:**
`transactionId` is None

### Environment

* **Python version:** 3.10
* **DipDup version or commit hash:** 6.2.0
* **Database engine version:** Postgres 14
* **Hasura version:** 2.2.0
* **Are you in docker?** Yes
* **Can you reproduce this issue on `master`?** Yes
